#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : The Environmental AI book # The title of the book. Will be placed in the left navbar.
author                      : The Environmental AI Community  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

#######################################################################################
# Execution settings
execute:
  execute_notebooks: cache # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: -1 # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'
  only_build_toc_files: true

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use jupyterbook-latex for pdf builds as default

#######################################################################################
# bibtex-specific settings
bibtex_bibfiles:
  - _bibliography/references.bib

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://binder.pangeo.io  # The URL of the BinderHub (e.g., https://mybinder.org or https://binder.pangeo.io)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button      : true  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in

repository:
  url: https://github.com/acocac/environmental-ai-book # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          : ['sphinxcontrib.bibtex'] # A list of extra extensions to load by Sphinx.
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
    language                : en